/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 web6.glb --transform
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/web6-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.web3.geometry} material={materials['Material.001']} position={[-137.49, 0, -37.54]} rotation={[0, -0.02, 0]} />
    </group>
  )
}

useGLTF.preload('/web6-transformed.glb')
